name: Live Deployment

on:
  push:
    branches:
      - main

env:
  VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
  VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID }}

jobs:
  deploy-production-live:
    uses: ./.github/workflows/deploy.yml
    if: github.ref_name == 'main'
    with:
      environment: production
      preview: false
    secrets: inherit
