name: Preview Deployment

on:
  pull_request:
    branches:
      - main

env:
  VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
  VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID }}

jobs:
  deploy-production-preview:
    uses: ./.github/workflows/deploy.yml
    if: github.base_ref == 'main'
    with:
      environment: production
      preview: true
    secrets: inherit
